/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editorconeventos;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Arturo
 */
public class VentanaEditor extends javax.swing.JFrame {

    private String titulo = "Editor de Texto RALL";

    /**
     * Creates new form VentanaEditor
     */
    public VentanaEditor() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/rall.png"));
            setIconImage(icon);
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Nuevo documento - " + getTitulo());
    }

    public void addEventos(OyenteEditor oyente) {
        opcionAbrir.addActionListener(oyente);
        toolAbrir.addActionListener(oyente);
        opcionGuardar.addActionListener(oyente);
        opcionCopiar.addActionListener(oyente);
        toolCopiar.addActionListener(oyente);
        opcionPegar.addActionListener(oyente);
        toolPegar.addActionListener(oyente);
        opcionCortar.addActionListener(oyente);
        opcionLimpiar.addActionListener(oyente);
        opcionNuevo.addActionListener(oyente);
        opcionAnalisisLexico.addActionListener(oyente);
        opcionAnalisisSintactico.addActionListener(oyente);
        opcionSobre.addActionListener(oyente);
        opcionGuardarComo.addActionListener(oyente);
        toolGuardar.addActionListener(oyente);
        opcionCompilar.addActionListener(oyente);
        opcionIniciar.addActionListener(oyente);
        toolSalir.addActionListener(oyente);
        toolCompilar.addActionListener(oyente);
        toolCorrer.addActionListener(oyente);
        addWindowListener(oyente);
    }

    public void mostrarAcercade() {
        DialogoSobre sobre = new DialogoSobre(this, true);
        sobre.setTitle("Sobre el autor");
        sobre.setSize(420, 380);
        sobre.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        sobre.setResizable(false);
        sobre.setLocationRelativeTo(this);
        sobre.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        toolAbrir = new javax.swing.JButton();
        toolGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        toolCopiar = new javax.swing.JButton();
        toolPegar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        toolCompilar = new javax.swing.JButton();
        toolCorrer = new javax.swing.JButton();
        toolSalir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionNuevo = new javax.swing.JMenuItem();
        opcionAbrir = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        opcionGuardar = new javax.swing.JMenuItem();
        opcionGuardarComo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        opcionCortar = new javax.swing.JMenuItem();
        opcionCopiar = new javax.swing.JMenuItem();
        opcionPegar = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        opcionLimpiar = new javax.swing.JMenuItem();
        menuAnalizar = new javax.swing.JMenu();
        opcionAnalisisLexico = new javax.swing.JMenuItem();
        opcionAnalisisSintactico = new javax.swing.JMenuItem();
        menuEjecutar = new javax.swing.JMenu();
        opcionCompilar = new javax.swing.JMenuItem();
        opcionIniciar = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenu();
        opcionPreferencias = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        opcionSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        toolBar.setRollover(true);

        toolAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/abrir-tool.png"))); // NOI18N
        toolAbrir.setFocusable(false);
        toolAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolAbrir.setName("abrir"); // NOI18N
        toolAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolAbrir);

        toolGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar-tool.png"))); // NOI18N
        toolGuardar.setFocusable(false);
        toolGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolGuardar.setName("guardar"); // NOI18N
        toolGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolGuardar);
        toolBar.add(jSeparator1);

        toolCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cortar-tool.png"))); // NOI18N
        toolCopiar.setFocusable(false);
        toolCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolCopiar.setName("copiar"); // NOI18N
        toolCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolCopiar);

        toolPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/copiar-tool.png"))); // NOI18N
        toolPegar.setFocusable(false);
        toolPegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolPegar.setName("pegar"); // NOI18N
        toolPegar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolPegar);
        toolBar.add(jSeparator2);

        toolCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479215449_tick_16.png"))); // NOI18N
        toolCompilar.setFocusable(false);
        toolCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolCompilar.setName("compilar"); // NOI18N
        toolCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolCompilar);

        toolCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479215464_right_16.png"))); // NOI18N
        toolCorrer.setFocusable(false);
        toolCorrer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolCorrer.setName("ejecutar"); // NOI18N
        toolCorrer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolCorrer);

        toolSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479215475_block_16.png"))); // NOI18N
        toolSalir.setFocusable(false);
        toolSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolSalir.setName("salir"); // NOI18N
        toolSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(toolSalir);
        toolBar.add(jSeparator3);

        getContentPane().add(toolBar, java.awt.BorderLayout.PAGE_START);

        barraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuArchivo.setText("Archivo");

        opcionNuevo.setText("Nuevo");
        opcionNuevo.setName("nuevo"); // NOI18N
        menuArchivo.add(opcionNuevo);

        opcionAbrir.setText("Abrir");
        opcionAbrir.setName("abrir"); // NOI18N
        menuArchivo.add(opcionAbrir);
        menuArchivo.add(jSeparator4);

        opcionGuardar.setText("Guardar");
        opcionGuardar.setName("guardar"); // NOI18N
        menuArchivo.add(opcionGuardar);

        opcionGuardarComo.setText("Guardar como...");
        opcionGuardarComo.setName("guardarcomo"); // NOI18N
        menuArchivo.add(opcionGuardarComo);
        menuArchivo.add(jSeparator5);

        opcionSalir.setText("Salir");
        menuArchivo.add(opcionSalir);

        barraMenu.add(menuArchivo);

        menuEditar.setText("Editar");

        opcionCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icon.png"))); // NOI18N
        opcionCortar.setText("Cortar");
        opcionCortar.setName("cortar"); // NOI18N
        menuEditar.add(opcionCortar);

        opcionCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cortar-tool.png"))); // NOI18N
        opcionCopiar.setText("Copiar");
        opcionCopiar.setName("copiar"); // NOI18N
        menuEditar.add(opcionCopiar);

        opcionPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/copiar-tool.png"))); // NOI18N
        opcionPegar.setText("Pegar");
        opcionPegar.setName("pegar"); // NOI18N
        menuEditar.add(opcionPegar);
        menuEditar.add(jSeparator6);

        opcionLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479216452_monitor_16.png"))); // NOI18N
        opcionLimpiar.setText("Limpiar Consola");
        opcionLimpiar.setName("limpiar"); // NOI18N
        menuEditar.add(opcionLimpiar);

        barraMenu.add(menuEditar);

        menuAnalizar.setText("Analizar");

        opcionAnalisisLexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479215464_right_16.png"))); // NOI18N
        opcionAnalisisLexico.setText("Análisis Léxico");
        opcionAnalisisLexico.setName("lexico"); // NOI18N
        menuAnalizar.add(opcionAnalisisLexico);

        opcionAnalisisSintactico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479215464_right_16.png"))); // NOI18N
        opcionAnalisisSintactico.setText("Análisis Sintáctico - Semántico");
        opcionAnalisisSintactico.setName("sintactico"); // NOI18N
        menuAnalizar.add(opcionAnalisisSintactico);

        barraMenu.add(menuAnalizar);

        menuEjecutar.setText("Ejecutar");

        opcionCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479215449_tick_16.png"))); // NOI18N
        opcionCompilar.setText("Compilar Programa");
        opcionCompilar.setName("compilar"); // NOI18N
        menuEjecutar.add(opcionCompilar);

        opcionIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/play.png"))); // NOI18N
        opcionIniciar.setText("Iniciar Programa");
        opcionIniciar.setName("iniciar"); // NOI18N
        menuEjecutar.add(opcionIniciar);

        barraMenu.add(menuEjecutar);

        menuConfiguracion.setText("Configuracion");

        opcionPreferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1479216571_gear_16.png"))); // NOI18N
        opcionPreferencias.setText("Preferencias");
        menuConfiguracion.add(opcionPreferencias);

        barraMenu.add(menuConfiguracion);

        menuAyuda.setText("Ayuda");

        opcionSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda.png"))); // NOI18N
        opcionSobre.setText("Acerca de");
        opcionSobre.setName("sobre"); // NOI18N
        menuAyuda.add(opcionSobre);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public final String getTitulo() {
        return titulo;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuAnalizar;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuConfiguracion;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuEjecutar;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenuItem opcionAnalisisLexico;
    private javax.swing.JMenuItem opcionAnalisisSintactico;
    private javax.swing.JMenuItem opcionCompilar;
    private javax.swing.JMenuItem opcionCopiar;
    private javax.swing.JMenuItem opcionCortar;
    private javax.swing.JMenuItem opcionGuardar;
    private javax.swing.JMenuItem opcionGuardarComo;
    private javax.swing.JMenuItem opcionIniciar;
    private javax.swing.JMenuItem opcionLimpiar;
    private javax.swing.JMenuItem opcionNuevo;
    private javax.swing.JMenuItem opcionPegar;
    private javax.swing.JMenuItem opcionPreferencias;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JMenuItem opcionSobre;
    private javax.swing.JButton toolAbrir;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JButton toolCompilar;
    private javax.swing.JButton toolCopiar;
    private javax.swing.JButton toolCorrer;
    private javax.swing.JButton toolGuardar;
    private javax.swing.JButton toolPegar;
    private javax.swing.JButton toolSalir;
    // End of variables declaration//GEN-END:variables
}
