/* Generated By:JavaCC: Do not edit this line. lexicoTreeConstants.java Version 5.0 */
package analizador;

public interface lexicoTreeConstants
{
  public int JJTINICIARANALISISLEXICO = 0;
  public int JJTINICIARANALISISSINTACTICO = 1;
  public int JJTBLOQUE = 2;
  public int JJTDECLARACIONCONSTANTES = 3;
  public int JJTDECLARACIONVARIABLES = 4;
  public int JJTVALORASIGNACION = 5;
  public int JJTOPERACION = 6;
  public int JJTARREGLO = 7;
  public int JJTINDICE = 8;
  public int JJTCREARFUNCION = 9;
  public int JJTFUNCION = 10;
  public int JJTLLAMARFUNCION = 11;
  public int JJTARGUMENTOE = 12;
  public int JJTARGUMENTOF = 13;
  public int JJTRETORNARVALOR = 14;
  public int JJTCREARPILA = 15;
  public int JJTPILAPUSH = 16;
  public int JJTPILAPOP = 17;
  public int JJTCREARLISTA = 18;
  public int JJTLISTAADD = 19;
  public int JJTLISTAGET = 20;
  public int JJTTIPOINTEGER = 21;
  public int JJTTIPOFLOAT = 22;
  public int JJTTIPOBOOLEAN = 23;
  public int JJTTIPOCHARACTER = 24;
  public int JJTTIPOSTRING = 25;
  public int JJTTIPOVOID = 26;
  public int JJTTIPOLIST = 27;
  public int JJTTIPOSTACK = 28;
  public int JJTVALORNUMEROENTERO = 29;
  public int JJTVALORNUMERODECIMAL = 30;
  public int JJTVALORCARACTER = 31;
  public int JJTVALORTRUE = 32;
  public int JJTVALORFALSE = 33;
  public int JJTVALORCADENA = 34;
  public int JJTIDENTIFICADOR = 35;
  public int JJTIMPRESION = 36;
  public int JJTASIGNACION = 37;
  public int JJTENTRADA = 38;
  public int JJTOPERADORMULTIPLICAR = 39;
  public int JJTOPERADORDIVIDIR = 40;
  public int JJTOPERADORSUMAR = 41;
  public int JJTOPERADORRESTAR = 42;
  public int JJTMENOR = 43;
  public int JJTMAYOR = 44;
  public int JJTIGUAL = 45;
  public int JJTMENORIGUAL = 46;
  public int JJTMAYORIGUAL = 47;
  public int JJTDIFERENTE = 48;
  public int JJTDECISIONIF = 49;
  public int JJTDECISIONELSE = 50;
  public int JJTEXPRESIONLOGICA = 51;
  public int JJTEXPRESIONSIMPLE = 52;
  public int JJTEXPRESIONBOOLEAN = 53;
  public int JJTOPERADOROR = 54;
  public int JJTOPERADORAND = 55;
  public int JJTCICLODOWHILE = 56;
  public int JJTCICLOWHILE = 57;
  public int JJTCICLOFOR = 58;
  public int JJTINICIALIZACION = 59;
  public int JJTVARIABLE = 60;
  public int JJTINCREMENTOS = 61;


  public String[] jjtNodeName = {
    "iniciarAnalisisLexico",
    "iniciarAnalisisSintactico",
    "bloque",
    "declaracionConstantes",
    "declaracionVariables",
    "valorAsignacion",
    "operacion",
    "arreglo",
    "indice",
    "crearFuncion",
    "funcion",
    "llamarFuncion",
    "argumentoe",
    "argumentof",
    "retornarValor",
    "crearPila",
    "pilaPush",
    "pilaPop",
    "crearLista",
    "listaAdd",
    "listaGet",
    "tipoInteger",
    "tipoFloat",
    "tipoBoolean",
    "tipoCharacter",
    "tipoString",
    "tipoVoid",
    "tipoList",
    "tipoStack",
    "valorNumeroEntero",
    "valorNumeroDecimal",
    "valorCaracter",
    "valorTrue",
    "valorFalse",
    "valorCadena",
    "identificador",
    "impresion",
    "asignacion",
    "entrada",
    "operadorMultiplicar",
    "operadorDividir",
    "operadorSumar",
    "operadorRestar",
    "Menor",
    "Mayor",
    "Igual",
    "MenorIgual",
    "MayorIgual",
    "Diferente",
    "decisionIF",
    "decisionELSE",
    "expresionLogica",
    "expresionSimple",
    "expresionBoolean",
    "operadorOR",
    "operadorAND",
    "cicloDoWhile",
    "cicloWhile",
    "cicloFor",
    "inicializacion",
    "variable",
    "incrementos",
  };
}
/* JavaCC - OriginalChecksum=dea32a0890a273557d4f2e4fe26646a5 (do not edit this line) */
