/* Generated By:JavaCC: Do not edit this line. lexicoConstants.java */
package analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 1;
  /** RegularExpression Id. */
  int CONSTANTE = 2;
  /** RegularExpression Id. */
  int INPUT = 3;
  /** RegularExpression Id. */
  int PRINT = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int ASIGNACION = 15;
  /** RegularExpression Id. */
  int RESTA = 16;
  /** RegularExpression Id. */
  int SUMA = 17;
  /** RegularExpression Id. */
  int MULTIPLICACION = 18;
  /** RegularExpression Id. */
  int DIVISION = 19;
  /** RegularExpression Id. */
  int MENOR = 20;
  /** RegularExpression Id. */
  int MAYOR = 21;
  /** RegularExpression Id. */
  int MENORIGUAL = 22;
  /** RegularExpression Id. */
  int MAYORIGUAL = 23;
  /** RegularExpression Id. */
  int IGUAL = 24;
  /** RegularExpression Id. */
  int DIFERENTE = 25;
  /** RegularExpression Id. */
  int PARENTA = 26;
  /** RegularExpression Id. */
  int PARENTC = 27;
  /** RegularExpression Id. */
  int LLAVEA = 28;
  /** RegularExpression Id. */
  int LLAVEC = 29;
  /** RegularExpression Id. */
  int COMA = 30;
  /** RegularExpression Id. */
  int PUNTO = 31;
  /** RegularExpression Id. */
  int PCOMA = 32;
  /** RegularExpression Id. */
  int DCOMA = 33;
  /** RegularExpression Id. */
  int SCOMA = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int FLOAT = 36;
  /** RegularExpression Id. */
  int BOOLEAN = 37;
  /** RegularExpression Id. */
  int CHAR = 38;
  /** RegularExpression Id. */
  int STR = 39;
  /** RegularExpression Id. */
  int NUMERO = 40;
  /** RegularExpression Id. */
  int DECIMAL = 41;
  /** RegularExpression Id. */
  int CADENA = 42;
  /** RegularExpression Id. */
  int CARACTER = 43;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"main\"",
    "\"const\"",
    "\"input\"",
    "\"print\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"int\"",
    "\"float\"",
    "\"boolean\"",
    "\"char\"",
    "\"string\"",
    "<NUMERO>",
    "<DECIMAL>",
    "<CADENA>",
    "<CARACTER>",
    "<IDENTIFICADOR>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
