/* Generated By:JavaCC: Do not edit this line. lexicoTreeConstants.java Version 5.0 */
package analizador;

public interface lexicoTreeConstants
{
  public int JJTINICIARANALISISLEXICO = 0;
  public int JJTINICIARANALISISSINTACTICO = 1;
  public int JJTBLOQUE = 2;
  public int JJTDECLARACIONCONSTANTES = 3;
  public int JJTDECLARACIONVARIABLES = 4;
  public int JJTVALORASIGNACION = 5;
  public int JJTOPERACION = 6;
  public int JJTARREGLO = 7;
  public int JJTINDICE = 8;
  public int JJTTIPOINTEGER = 9;
  public int JJTTIPOFLOAT = 10;
  public int JJTTIPOBOOLEAN = 11;
  public int JJTTIPOCHARACTER = 12;
  public int JJTTIPOSTRING = 13;
  public int JJTVALORNUMEROENTERO = 14;
  public int JJTVALORNUMERODECIMAL = 15;
  public int JJTVALORCARACTER = 16;
  public int JJTVALORTRUE = 17;
  public int JJTVALORFALSE = 18;
  public int JJTVALORCADENA = 19;
  public int JJTIDENTIFICADOR = 20;
  public int JJTIMPRESION = 21;
  public int JJTASIGNACION = 22;
  public int JJTENTRADA = 23;
  public int JJTOPERADORMULTIPLICAR = 24;
  public int JJTOPERADORDIVIDIR = 25;
  public int JJTOPERADORSUMAR = 26;
  public int JJTOPERADORRESTAR = 27;
  public int JJTMENOR = 28;
  public int JJTMAYOR = 29;
  public int JJTIGUAL = 30;
  public int JJTMENORIGUAL = 31;
  public int JJTMAYORIGUAL = 32;
  public int JJTDIFERENTE = 33;
  public int JJTDECISIONIF = 34;
  public int JJTDECISIONELSE = 35;
  public int JJTEXPRESIONLOGICA = 36;
  public int JJTEXPRESIONSIMPLE = 37;
  public int JJTEXPRESIONBOOLEAN = 38;
  public int JJTOPERADOROR = 39;
  public int JJTOPERADORAND = 40;
  public int JJTCICLODOWHILE = 41;
  public int JJTCICLOWHILE = 42;
  public int JJTCICLOFOR = 43;
  public int JJTINICIALIZACION = 44;
  public int JJTVARIABLE = 45;
  public int JJTINCREMENTOS = 46;


  public String[] jjtNodeName = {
    "iniciarAnalisisLexico",
    "iniciarAnalisisSintactico",
    "bloque",
    "declaracionConstantes",
    "declaracionVariables",
    "valorAsignacion",
    "operacion",
    "arreglo",
    "indice",
    "tipoInteger",
    "tipoFloat",
    "tipoBoolean",
    "tipoCharacter",
    "tipoString",
    "valorNumeroEntero",
    "valorNumeroDecimal",
    "valorCaracter",
    "valorTrue",
    "valorFalse",
    "valorCadena",
    "identificador",
    "impresion",
    "asignacion",
    "entrada",
    "operadorMultiplicar",
    "operadorDividir",
    "operadorSumar",
    "operadorRestar",
    "Menor",
    "Mayor",
    "Igual",
    "MenorIgual",
    "MayorIgual",
    "Diferente",
    "decisionIF",
    "decisionELSE",
    "expresionLogica",
    "expresionSimple",
    "expresionBoolean",
    "operadorOR",
    "operadorAND",
    "cicloDoWhile",
    "cicloWhile",
    "cicloFor",
    "inicializacion",
    "variable",
    "incrementos",
  };
}
/* JavaCC - OriginalChecksum=940f5ed6bdf4bd4b3ea0a338ca690b8d (do not edit this line) */
